runtime: custom
env: flex
service: checklogin

runtime_config:
  runtime_version: "8"
  operating_system: "ubuntu22"
  
instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  ASPNETCORE_URLS: "http://*:8080"

handlers:
- url: /.*
  script: auto
